### PR TITLE
Added custom cartridge properties multi-line text field to load cartridge

### PR DESCRIPTION
**Pull request by RobertNorthard**
Added custom cartridge properties multi-line text field to load cartridge to support custom properties

e.g.
sonar.projectKey=adop
openshift.projectName=adop-dev

Cartridges can then parse this text field and be configured according to the provided properties. Cartridges that adopt approach will have greater  re-usability. 

The library to consume these custom properties can be found here: https://github.com/RobertNorthard/adop-dsl-custom-cartridge-properties

I have also updated the skeleton cartridge as an example of how to use the library:
https://github.com/Accenture/adop-cartridge-skeleton/pull/6

Signed-off-by: Northard, Robert A <robert.a.northard@accenture.com>

### CODE REVIEW

**Comment by nickdgriffin** [comment]
I think we need to include loading in the library so that at least those "in the know" can make use of it, and maybe some documentation on how to consume and make use of it (in the main documentation & cartridge cookbook).

This is dependent on Accenture/adop-platform-management#11 going in first too.

**Comment by dsingh07** [comment]
@RobertNorthard Thanks for the PR, happy to merge! Can you squash your commits please?

**Comment by RobertNorthard** [comment]
This is dependent on https://github.com/Accenture/adop-platform-management/pull/55

**Comment by dsingh07** [comment]
@RobertNorthard Can you rebase on master so latest changes that have gone in for the Jenkins upgrade are included?

**Comment by RobertNorthard** [comment]
@dsingh07 rebased.

**Comment by Dimbu-Afonso** [comment]
@dsingh07 tested and ready to merge

**Pull request merged**
